### ISSUE TITLE
how to navigate to another UIViewController, choose something and return it to the first VC?

### ISSUE THREAD

**Issue by haemi** [FortechRomania/ios-mvp-clean-architecture#10]
On my first UIViewController, I have a button which leads to another VC with a list of entries. When I select an entry on this, I would like to return it back to the first UIViewController.

But currently I really have problems implementing this with this architecture...

**Comment by cosminstirbu** [comment]
Hi,

You can use the delegate pattern.
For instance [AddBookPresenter](https://github.com/FortechRomania/ios-mvp-clean-architecture/blob/master/Library/Scenes/AddBook/AddBookPresenter.swift) notifies its delegate ([BooksPresenter](https://github.com/FortechRomania/ios-mvp-clean-architecture/blob/master/Library/Scenes/Books/BooksPresenter.swift)) that a `Book` was added.

You can do something similar, notifying that an entry was selected, by passing back either the entry itself or the selected index path.

Regards,
Cosmin

**Comment by haemi** [comment]
sorry, didn't see that you already answered long time ago... thanks a lot!

I'm using this architecture in my current project, would love to open issues if I have questions/discussion material, if that's ok for you!
