### ISSUE TITLE
Api call for multiple use cases

### ISSUE THREAD

**Issue by Cortlandd** [FortechRomania/ios-mvp-clean-architecture#17]
I have a viewcontroller that has multiple usecases, both of which make calls to an Api and does so on viewcontroller load. Currently, a operationqueue calls the usecases 1 at a time. How would I approach making these calls concurrent? I want both usecases to have their own thread to make their call on load.

**Comment by cosminstirbu** [comment]
[OperationQueue](https://developer.apple.com/documentation/foundation/operationqueue) is concurrent by default, so as long as you call `func addOperation(_ block: @escaping () -> Void)` to run your use case then all use cases should run concurrently (you might want to have a look at `var maxConcurrentOperationCount: Int { get set }` as well).

**Comment by cosminstirbu** [comment]
This [tutorial](https://medium.com/@aliakhtar_16369/concurrency-in-swift-operations-and-operation-queue-part-3-a108fbe27d61) might help as well.

**Comment by Cortlandd** [comment]
Where would I call `addOperation()`

**Comment by Cortlandd** [comment]
👍🏾
