### ISSUE TITLE
Passing deleted/added book to the Books Scene

### ISSUE THREAD

**Issue by hasanalbukhari** [FortechRomania/ios-mvp-clean-architecture#18]
It's not really an issue.

But, how we should do that without breaking the MVP?

Great work by the way :)

**Comment by cosminstirbu** [comment]
We already pass the added book - you can have a look at `AddBookPresenterDelegate`.

Something similar could be done for delete as well.

**Comment by hasanalbukhari** [comment]
Presenters communicates through delegates. Great TY.
